"""Lab catalog, ordering, result entry, sign-off, and file security rules.

Lab result uploads intentionally use a private filesystem directory rather than
the public static mount. The stored filename is generated by the server, never
derived from the client filename, and only the relative generated path is
persisted. Upload validation is repeated on the server: the byte size is capped
before persistence, the extension is allowlisted, the declared content type
must match the allowlist, and the file signature must match the declared type
(PDF, PNG, JPEG, or WEBP). This prevents relying on a browser picker, blocks
common polyglot or renamed-file mistakes, and avoids path traversal. Download
routes resolve the generated path beneath the private root and perform the
clinic, patient, and clinical-role authorization check before returning a file.
"""

from __future__ import annotations

from datetime import datetime, timezone
import os
from pathlib import Path
from typing import Any
from uuid import uuid4

from sqlalchemy import select
from sqlalchemy.orm import Session, joinedload, selectinload

from app.models import (
    AuditAction,
    LabOrder,
    LabOrderSet,
    LabOrderStatus,
    LabResult,
    LabTestDefinition,
    User,
    UserRole,
    Visit,
)
from app.services.audit import record_audit_event
from app.services.clinical import CLINICAL_ROLES, ensure_clinical_role

LAB_RESULT_MAX_BYTES = 10 * 1024 * 1024
LAB_UPLOAD_ROOT = Path(os.getenv("LAB_UPLOAD_DIR", "var/lab_results"))
DEFAULT_LAB_TESTS: tuple[tuple[str, str], ...] = (
    ("CBC", "Complete blood count"),
    ("Urinalysis", "Urinalysis with microscopy when indicated"),
    ("Glucose screen", "Pregnancy glucose screening"),
    ("Rh/blood type", "ABO and Rh blood typing"),
    ("STI panel", "Clinic-defined sexually transmitted infection panel"),
    ("Pap/HPV", "Cervical cytology and HPV testing"),
    ("TSH", "Thyroid-stimulating hormone"),
)
ALLOWED_LAB_FILES = {
    ".pdf": ("application/pdf",),
    ".png": ("image/png",),
    ".jpg": ("image/jpeg",),
    ".jpeg": ("image/jpeg",),
    ".webp": ("image/webp",),
}


def _same_clinic(actor: User, clinic_id: int) -> None:
    if actor.clinic_id != clinic_id:
        raise PermissionError("The record does not belong to this clinic.")


def _clinic_visit(db: Session, actor: User, visit_id: int) -> Visit:
    visit = db.scalar(
        select(Visit).where(
            Visit.id == visit_id,
            Visit.clinic_id == actor.clinic_id,
        )
    )
    if visit is None:
        raise ValueError("Visit not found in this clinic.")
    return visit


def ensure_default_lab_test_definitions(
    db: Session,
    clinic_id: int,
) -> list[LabTestDefinition]:
    """Seed the starter catalog once for a clinic that has no catalog rows."""

    existing = list(
        db.scalars(
            select(LabTestDefinition).where(
                LabTestDefinition.clinic_id == clinic_id,
            )
        )
    )
    if existing:
        return existing
    definitions = [
        LabTestDefinition(
            clinic_id=clinic_id,
            name=name,
            description=description,
            active=True,
        )
        for name, description in DEFAULT_LAB_TESTS
    ]
    db.add_all(definitions)
    db.flush()
    return definitions


def get_lab_test_definitions(
    db: Session,
    clinic_id: int,
    *,
    active_only: bool = False,
) -> list[LabTestDefinition]:
    """Return a clinic's catalog, seeding the starter list when necessary."""

    ensure_default_lab_test_definitions(db, clinic_id)
    conditions = [LabTestDefinition.clinic_id == clinic_id]
    if active_only:
        conditions.append(LabTestDefinition.active.is_(True))
    return list(
        db.scalars(
            select(LabTestDefinition)
            .where(*conditions)
            .order_by(LabTestDefinition.name.asc())
        )
    )


def get_lab_order_sets(
    db: Session,
    clinic_id: int,
    *,
    active_only: bool = False,
) -> list[LabOrderSet]:
    """Return clinic order bundles with their test definitions."""

    conditions = [LabOrderSet.clinic_id == clinic_id]
    if active_only:
        conditions.append(LabOrderSet.active.is_(True))
    return list(
        db.scalars(
            select(LabOrderSet)
            .options(selectinload(LabOrderSet.test_definitions))
            .where(*conditions)
            .order_by(LabOrderSet.name.asc())
        )
    )


def create_lab_test_definition(
    db: Session,
    actor: User,
    name: str,
    description: str,
) -> LabTestDefinition:
    """Create a clinic test definition; only clinic admins may edit the catalog."""

    if actor.role is not UserRole.CLINIC_ADMIN:
        raise PermissionError("Only clinic_admin can manage lab definitions.")
    normalized_name = name.strip()
    if not normalized_name:
        raise ValueError("Lab test name is required.")
    duplicate = db.scalar(
        select(LabTestDefinition).where(
            LabTestDefinition.clinic_id == actor.clinic_id,
            LabTestDefinition.name == normalized_name,
        )
    )
    if duplicate is not None:
        raise ValueError("A lab test with this name already exists.")
    definition = LabTestDefinition(
        clinic_id=actor.clinic_id,
        name=normalized_name,
        description=description.strip(),
    )
    db.add(definition)
    db.flush()
    record_audit_event(
        db,
        actor.id,
        AuditAction.CREATE,
        "lab_test_definition",
        definition.id,
    )
    return definition


def update_lab_test_definition(
    db: Session,
    definition: LabTestDefinition,
    actor: User,
    name: str,
    description: str,
    active: bool,
) -> LabTestDefinition:
    """Update a clinic test definition or deactivate it without deleting history."""

    if actor.role is not UserRole.CLINIC_ADMIN:
        raise PermissionError("Only clinic_admin can manage lab definitions.")
    _same_clinic(actor, definition.clinic_id)
    normalized_name = name.strip()
    if not normalized_name:
        raise ValueError("Lab test name is required.")
    duplicate = db.scalar(
        select(LabTestDefinition).where(
            LabTestDefinition.clinic_id == definition.clinic_id,
            LabTestDefinition.name == normalized_name,
            LabTestDefinition.id != definition.id,
        )
    )
    if duplicate is not None:
        raise ValueError("A lab test with this name already exists.")
    changed: list[str] = []
    for field, value in (
        ("name", normalized_name),
        ("description", description.strip()),
        ("active", active),
    ):
        if getattr(definition, field) != value:
            setattr(definition, field, value)
            changed.append(field)
    if changed:
        record_audit_event(
            db,
            actor.id,
            AuditAction.UPDATE,
            "lab_test_definition",
            definition.id,
            details={"fields": changed},
        )
    return definition


def _definitions_for_clinic(
    db: Session,
    clinic_id: int,
    definition_ids: list[int],
) -> list[LabTestDefinition]:
    ids = list(dict.fromkeys(definition_ids))
    if not ids:
        return []
    definitions = list(
        db.scalars(
            select(LabTestDefinition).where(
                LabTestDefinition.id.in_(ids),
                LabTestDefinition.clinic_id == clinic_id,
                LabTestDefinition.active.is_(True),
            )
        )
    )
    if len(definitions) != len(ids):
        raise ValueError("One or more lab tests are unavailable.")
    return sorted(definitions, key=lambda item: ids.index(item.id))


def create_lab_order_set(
    db: Session,
    actor: User,
    name: str,
    description: str,
    definition_ids: list[int],
) -> LabOrderSet:
    """Create a named clinic bundle from active test definitions."""

    if actor.role is not UserRole.CLINIC_ADMIN:
        raise PermissionError("Only clinic_admin can manage lab order sets.")
    normalized_name = name.strip()
    if not normalized_name:
        raise ValueError("Order set name is required.")
    if not definition_ids:
        raise ValueError("Select at least one lab test.")
    duplicate = db.scalar(
        select(LabOrderSet).where(
            LabOrderSet.clinic_id == actor.clinic_id,
            LabOrderSet.name == normalized_name,
        )
    )
    if duplicate is not None:
        raise ValueError("An order set with this name already exists.")
    definitions = _definitions_for_clinic(db, actor.clinic_id, definition_ids)
    order_set = LabOrderSet(
        clinic_id=actor.clinic_id,
        name=normalized_name,
        description=description.strip(),
        test_definitions=definitions,
    )
    db.add(order_set)
    db.flush()
    record_audit_event(
        db,
        actor.id,
        AuditAction.CREATE,
        "lab_order_set",
        order_set.id,
    )
    return order_set


def update_lab_order_set(
    db: Session,
    order_set: LabOrderSet,
    actor: User,
    name: str,
    description: str,
    definition_ids: list[int],
    active: bool,
) -> LabOrderSet:
    """Edit an order bundle and its membership without changing old orders."""

    if actor.role is not UserRole.CLINIC_ADMIN:
        raise PermissionError("Only clinic_admin can manage lab order sets.")
    _same_clinic(actor, order_set.clinic_id)
    normalized_name = name.strip()
    if not normalized_name or not definition_ids:
        raise ValueError("Order set name and at least one lab test are required.")
    duplicate = db.scalar(
        select(LabOrderSet).where(
            LabOrderSet.clinic_id == order_set.clinic_id,
            LabOrderSet.name == normalized_name,
            LabOrderSet.id != order_set.id,
        )
    )
    if duplicate is not None:
        raise ValueError("An order set with this name already exists.")
    definitions = _definitions_for_clinic(
        db,
        order_set.clinic_id,
        definition_ids,
    )
    changed: list[str] = []
    if order_set.name != normalized_name:
        order_set.name = normalized_name
        changed.append("name")
    if order_set.description != description.strip():
        order_set.description = description.strip()
        changed.append("description")
    if {item.id for item in order_set.test_definitions} != {
        item.id for item in definitions
    }:
        order_set.test_definitions = definitions
        changed.append("test_definitions")
    if order_set.active != active:
        order_set.active = active
        changed.append("active")
    if changed:
        record_audit_event(
            db,
            actor.id,
            AuditAction.UPDATE,
            "lab_order_set",
            order_set.id,
            details={"fields": changed},
        )
    return order_set


def order_lab_tests(
    db: Session,
    actor: User,
    visit_id: int,
    definition_ids: list[int],
    order_set_id: int | None = None,
) -> list[LabOrder]:
    """Create ordered rows for individual tests, an order set, or both."""

    ensure_clinical_role(actor)
    visit = _clinic_visit(db, actor, visit_id)
    selected_ids = list(definition_ids)
    order_set = None
    if order_set_id is not None:
        order_set = db.scalar(
            select(LabOrderSet)
            .options(selectinload(LabOrderSet.test_definitions))
            .where(
                LabOrderSet.id == order_set_id,
                LabOrderSet.clinic_id == actor.clinic_id,
                LabOrderSet.active.is_(True),
            )
        )
        if order_set is None:
            raise ValueError("Order set not found in this clinic.")
        selected_ids.extend(item.id for item in order_set.test_definitions)
    definitions = _definitions_for_clinic(
        db,
        actor.clinic_id,
        selected_ids,
    )
    if not definitions:
        raise ValueError("Select at least one lab test or order set.")
    orders = [
        LabOrder(
            clinic_id=actor.clinic_id,
            visit_id=visit.id,
            patient_id=visit.patient_id,
            lab_test_definition=definition,
            order_set=order_set,
            ordered_by_user_id=actor.id,
            status=LabOrderStatus.ORDERED,
        )
        for definition in definitions
    ]
    db.add_all(orders)
    db.flush()
    for order in orders:
        record_audit_event(
            db,
            actor.id,
            AuditAction.CREATE,
            "lab_order",
            order.id,
            details={
                "visit_id": visit.id,
                "lab_test_definition_id": order.lab_test_definition_id,
                "order_set_id": order_set_id,
            },
        )
    return orders


def get_visit_lab_orders(
    db: Session,
    actor: User,
    visit_id: int,
) -> list[LabOrder]:
    """Return active lab orders attached to an authorized visit."""

    ensure_clinical_role(actor)
    _clinic_visit(db, actor, visit_id)
    return list(
        db.scalars(
            select(LabOrder)
            .options(
                joinedload(LabOrder.lab_test_definition),
                joinedload(LabOrder.order_set),
                joinedload(LabOrder.result).joinedload(LabResult.reviewed_by_user),
            )
            .where(
                LabOrder.clinic_id == actor.clinic_id,
                LabOrder.visit_id == visit_id,
            )
            .order_by(LabOrder.ordered_at.desc(), LabOrder.id.desc())
        )
    )


def get_pending_lab_orders(
    db: Session,
    actor: User,
) -> list[LabOrder]:
    """Return outstanding orders that have not received any result."""

    ensure_clinical_role(actor)
    return list(
        db.scalars(
            select(LabOrder)
            .options(
                joinedload(LabOrder.patient),
                joinedload(LabOrder.visit),
                joinedload(LabOrder.lab_test_definition),
            )
            .where(
                LabOrder.clinic_id == actor.clinic_id,
                LabOrder.status == LabOrderStatus.ORDERED,
            )
            .order_by(LabOrder.ordered_at.asc(), LabOrder.id.asc())
        )
    )


def _validate_uploaded_file(
    filename: str,
    content_type: str | None,
    content: bytes,
) -> tuple[str, str]:
    """Validate upload metadata and magic bytes before private persistence."""

    if len(content) > LAB_RESULT_MAX_BYTES:
        raise ValueError("Lab result files must be 10 MB or smaller.")
    safe_name = Path(filename or "").name
    suffix = Path(safe_name).suffix.lower()
    allowed_types = ALLOWED_LAB_FILES.get(suffix)
    if allowed_types is None:
        raise ValueError("Lab result files must be PDF, PNG, JPEG, or WEBP.")
    if content_type not in allowed_types:
        raise ValueError("The uploaded file type does not match its extension.")
    signature_matches = (
        (suffix == ".pdf" and content.startswith(b"%PDF-"))
        or (suffix == ".png" and content.startswith(b"\x89PNG\r\n\x1a\n"))
        or (suffix in {".jpg", ".jpeg"} and content.startswith(b"\xff\xd8\xff"))
        or (
            suffix == ".webp"
            and len(content) >= 12
            and content.startswith(b"RIFF")
            and content[8:12] == b"WEBP"
        )
    )
    if not signature_matches:
        raise ValueError("The uploaded file signature does not match its type.")
    return safe_name, content_type


def _store_lab_file(
    filename: str,
    content_type: str,
    content: bytes,
) -> tuple[str, str, int]:
    safe_name, validated_type = _validate_uploaded_file(
        filename,
        content_type,
        content,
    )
    LAB_UPLOAD_ROOT.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(LAB_UPLOAD_ROOT, 0o700)
    except OSError:
        pass
    generated_name = f"{uuid4().hex}{Path(safe_name).suffix.lower()}"
    target = LAB_UPLOAD_ROOT / generated_name
    with target.open("xb") as stored:
        stored.write(content)
    try:
        os.chmod(target, 0o600)
    except OSError:
        pass
    return generated_name, validated_type, len(content)


def create_lab_result(
    db: Session,
    order: LabOrder,
    actor: User,
    *,
    manual_value: str | None = None,
    filename: str | None = None,
    content_type: str | None = None,
    content: bytes | None = None,
) -> LabResult:
    """Enter exactly one manual or uploaded result and move the order to resulted."""

    ensure_clinical_role(actor)
    _same_clinic(actor, order.clinic_id)
    if order.result is not None:
        raise ValueError("This lab order already has a result.")
    normalized_value = (manual_value or "").strip()
    has_file = bool(filename or content_type or content)
    if not normalized_value and not has_file:
        raise ValueError("Enter a manual value or upload one result file.")
    stored_name = stored_type = None
    stored_size = None
    if has_file:
        if not filename or not content_type or content is None:
            raise ValueError("The uploaded result is incomplete.")
        stored_name, stored_type, stored_size = _store_lab_file(
            filename,
            content_type,
            content,
        )
    result = LabResult(
        lab_order=order,
        manual_value=normalized_value or None,
        file_path=stored_name,
        original_filename=Path(filename).name if stored_name and filename else None,
        content_type=stored_type,
        file_size=stored_size,
        entered_by_user_id=actor.id,
    )
    order.status = LabOrderStatus.RESULTED
    db.add(result)
    try:
        db.flush()
    except Exception:
        if stored_name:
            (LAB_UPLOAD_ROOT / stored_name).unlink(missing_ok=True)
        raise
    record_audit_event(
        db,
        actor.id,
        AuditAction.CREATE,
        "lab_result",
        result.id,
        details={"lab_order_id": order.id, "has_file": bool(stored_name)},
    )
    return result


def review_lab_result(
    db: Session,
    result: LabResult,
    actor: User,
) -> LabResult:
    """Require a physician to sign off a resulted lab."""

    ensure_clinical_role(actor)
    _same_clinic(actor, result.lab_order.clinic_id)
    if actor.role is not UserRole.PHYSICIAN:
        raise PermissionError("Only a physician can review lab results.")
    if result.lab_order.status is not LabOrderStatus.RESULTED:
        raise ValueError("Only resulted labs can be reviewed.")
    result.reviewed_by_user_id = actor.id
    result.reviewed_at = datetime.now(timezone.utc)
    result.lab_order.status = LabOrderStatus.REVIEWED
    db.flush()
    record_audit_event(
        db,
        actor.id,
        AuditAction.UPDATE,
        "lab_result",
        result.id,
        details={"status": LabOrderStatus.REVIEWED.value},
    )
    return result


def get_lab_result_for_user(
    db: Session,
    result_id: int,
    actor: User,
) -> LabResult:
    """Load a result only through the clinical user's clinic and patient scope."""

    ensure_clinical_role(actor)
    result = db.scalar(
        select(LabResult)
        .options(
            joinedload(LabResult.lab_order),
            joinedload(LabResult.reviewed_by_user),
        )
        .join(LabResult.lab_order)
        .where(
            LabResult.id == result_id,
            LabOrder.clinic_id == actor.clinic_id,
        )
    )
    if result is None:
        raise ValueError("Lab result not found in this clinic.")
    return result


def lab_file_path_for_result(result: LabResult) -> Path:
    """Resolve a stored result path beneath the private upload root only."""

    if not result.file_path:
        raise ValueError("This lab result does not have an uploaded file.")
    root = LAB_UPLOAD_ROOT.resolve()
    candidate = (root / result.file_path).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as error:
        raise ValueError("Invalid stored lab result path.") from error
    if not candidate.is_file():
        raise ValueError("The stored lab result file is unavailable.")
    return candidate